# Generated by Django 4.0.8 on 2023-06-08 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_is_conformed_usercomfirmation_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('mail', 'mail'), ('femail', 'femail')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must start from 9 and contain 12 characters. For example: 998998065999', regex='^9\\d{12}$')]),
        ),
    ]
